### ISSUE TITLE
Settings Panel Doesn't Always Close

### ISSUE THREAD

**Issue by lucknaumann** [Mirinsoft/CleanmgrPlus#3]
Hi,
The Settings panel doesn't always close. I often need to quit and relaunch for the Settings panel to be closed. Then, if I reopen Settings, it will usually still remain open. I'm using Windows 10 v.1809 b.17763.737. 

I also wanted to thank you for making this app as I am also wary of the deprecation to Disk Cleanup. I've recently discovered this app so I haven't used it much. I appreciate the dark themes available, too!
Edit: Request: Can the dark themes be present in the Settings panel as well? =]

**Comment by Mirinsoft** [comment]
Hi,

thanks for the feedback :)
Closing behavior of the Settings panel has been optimized with latest release 
https://github.com/Mirinsoft/CleanmgrPlus/releases/tag/v1.2.5.825

Dark themes are already integrated into the Settings panel. Just click on link "Choose a Theme"

Regards

**Comment by lucknaumann** [comment]
@Mirinsoft Great, thanks! 

Yeah, I saw the "Choose a Theme" link but I meant the settings panel itself remains white even when choosing another colored theme. I just thought it would be more overall aesthetic for the settings panel to also change with the theme and easier on the eyes. =)

**Comment by Mirinsoft** [comment]
I'm sorry, something went down the wrong way :(
Well, you make a good point, I'll put this on my to-do list for a future version.

Many thanks!

**Comment by lucknaumann** [comment]
You're welcome and thank you! =)
