### ISSUE TITLE
Reflecting multibyte characters

### ISSUE THREAD

**Issue by maboroshin** [mirinsoft/CleanmgrPlus#4]
Will multibyte characters be garbled? It is saved in UTF-8.
I don't know if I will translate it. But, nobody can't translate it.
This garbled character is common to Cleanmgr+ and CloneApp.

This is a garbled image of the inserted Japanese test string:
![clnmgr](https://user-images.githubusercontent.com/41102508/70797518-057e4180-1de8-11ea-917f-745ccf17bc22.png)

**Comment by Belim** [comment]
UTF-8 cannot be used for GUI translation as some controls doesn't support Unicode (currently).
I'm sry!
