### ISSUE TITLE
[Feature request] Add German localization for Data sets to repacked German version

### ISSUE THREAD

**Issue by snorreflorre** [mirinsoft/CleanmgrPlus#9]
**Is your feature request related to a problem? Please describe.**
Since [release 1.30.953](https://github.com/mirinsoft/CleanmgrPlus/releases/tag/1.30.953) you also offer a [repacked German version](https://www.mirinsoft.com/getapp/download/4-cleanmgrplus/9-cleanmgrplus-de) with every new release. This repacked version only contains the [localization for GUI](https://github.com/mirinsoft/CleanmgrPlus/blob/master/locales/locale_de.zip), but not [for Data sets](https://github.com/mirinsoft/CleanmgrPlus/blob/master/locales/windata_de.zip).

**Describe the solution you'd like**
Add German localization for Data sets to repacked German version.

**Describe alternatives you've considered**
Add localization options to the GUI.

Thanks in advance.

**Comment by Belim** [comment]
You are absolutely right. I've missed replacing the en-US data sat in latest release.  :confused:
Thanks for reporting

I've just updated the .ZIP package with the current data set ONLY. No further changes
https://www.mirinsoft.com/debotnet-packs/download/4-cleanmgrplus/9-cleanmgrplus-de

The gui is for the most part localizable. Only the log output is not. My focus hasn't been on it.

You are welcome to try this little project of mine. Another 1:1 replica of cleanmgr.exe + Storage sense https://github.com/mirinsoft/burnbytes
Localization is dependant on system locale but from the scope of services it doesn't come close to Cleanmgr+
